const API="https://pokeapi.co/api/v2",SHOWDOWN="https://play.pokemonshowdown.com/sprites/ani/",STATIC="https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/";
const PS="https://pokemonshowdown.com",REPLAYS="https://replay.pokemonshowdown.com";
const S={all:[],details:new Map(),team:[],selected:null,profile:null,replays:[],analysis:null,replayStats:[],patterns:[]};
const META={
 rillaboom:{usage:37.6,roles:["Fake Out","Grassy Terrain","Pivot"],partners:{sneasler:94,salamence:91,incineroar:88,kingambit:84,gholdengo:80}},
 sneasler:{usage:36.6,roles:["Fast pressure","Offense"],partners:{rillaboom:94,salamence:81,incineroar:82,farigiraf:78,gholdengo:76}},
 incineroar:{usage:28.5,roles:["Fake Out","Intimidate","Pivot"],partners:{rillaboom:88,salamence:84,sneasler:82,farigiraf:80,kingambit:79}},
 salamence:{usage:26,roles:["Mega","Offense","Speed control"],partners:{rillaboom:91,sneasler:81,incineroar:84,gholdengo:79,farigiraf:77}},
 kingambit:{usage:25,roles:["Offense","Late game"],partners:{rillaboom:84,sneasler:80,incineroar:79,salamence:78,farigiraf:76}},
 gholdengo:{usage:10.4,roles:["Special offense","Spread pressure"],partners:{rillaboom:80,salamence:79,sneasler:76,incineroar:75,farigiraf:73}},
 farigiraf:{usage:18,roles:["Trick Room","Anti-priority","Support"],partners:{rillaboom:77,incineroar:80,kingambit:76,salamence:77,gholdengo:73}},
 "indeedee-f":{usage:21.6,roles:["Psychic Terrain","Support","Redirection"],partners:{sneasler:70,farigiraf:74,gholdengo:73,kingambit:70}}
};
const types=["normal","fire","water","electric","grass","ice","fighting","poison","ground","flying","psychic","bug","rock","ghost","dragon","dark","steel","fairy"];
const cap=s=>s.replace(/\b\w/g,c=>c.toUpperCase()),gen=id=>id<=151?1:id<=251?2:id<=386?3:id<=493?4:id<=649?5:id<=721?6:id<=809?7:id<=905?8:9;
const find=id=>S.all.find(p=>p.id===id),findName=n=>S.all.find(p=>p.name===n),spriteTag=p=>`<img class="sprite" src="${SHOWDOWN}${p.name}.gif" onerror="this.onerror=null;this.src='${STATIC}${p.id}.png'" alt="${cap(p.name)}">`;
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
async function boot(){typeFilter.innerHTML+=types.map(t=>`<option>${t}</option>`).join("");try{const r=await fetch(`${API}/pokemon?limit=1025`);const d=await r.json();S.all=d.results.map((p,i)=>({id:i+1,name:p.name,url:p.url}));}catch(e){S.all=Object.keys(META).map((n,i)=>({id:i+1,name:n,url:""}));}makeBackground();renderList();renderAll();renderDex();newScenario();}
async function detail(id){if(S.details.has(id))return;try{const r=await fetch(`${API}/pokemon/${id}`),d=await r.json();S.details.set(id,{types:d.types.map(x=>x.type.name),abilities:d.abilities.map(x=>x.ability.name)});}catch{} }
function renderList(){const q=search.value.toLowerCase().trim(),t=typeFilter.value,g=genFilter.value;let a=S.all.filter(p=>(!q||p.name.includes(q))&&(!g||gen(p.id)==g));if(t)a=a.filter(p=>!S.details.has(p.id)||S.details.get(p.id).types.includes(t));a.sort((x,y)=>(META[y.name]?.usage||0)-(META[x.name]?.usage||0)||x.id-y.id);if(!metaOnly.checked)a.sort((x,y)=>x.id-y.id);a=a.slice(0,220);pokemonList.innerHTML=a.map(p=>`<button class="pokemon" data-id="${p.id}">${spriteTag(p)}<span>${cap(p.name)}</span><small>${META[p.name]?(META[p.name].usage.toFixed(1)+"% "):""}</small></button>`).join("");pokemonList.querySelectorAll(".pokemon").forEach(x=>x.onclick=()=>add(+x.dataset.id));a.slice(0,80).forEach(p=>detail(p.id));}
async function add(id){const p=find(id);if(!p||S.team.length>=6||S.team.some(x=>x.id===id))return;S.team.push(p);S.selected=p;await detail(id);renderAll();}
function remove(id){S.team=S.team.filter(x=>x.id!==id);S.selected=S.team.at(-1)||null;renderAll();}
function renderAll(){renderTeam();renderSynergy();renderDiagnosis();renderGameplan();renderTeamCoach();}
function renderTeam(){team.innerHTML=Array.from({length:6},(_,i)=>{const p=S.team[i];return p?`<div class="slot filled">${spriteTag(p)}<b>${cap(p.name)}</b><button class="ghost" onclick="remove(${p.id})">Quitar</button></div>`:`<div class="slot">Espacio ${i+1}<br>Vacío</div>`}).join("");}
function candidates(){const chosen=S.team.map(x=>x.name),base=S.selected?.name,s={};if(base&&META[base])Object.assign(s,META[base].partners);Object.keys(META).forEach(n=>{if(!chosen.includes(n)&&s[n]==null)s[n]=Math.round(META[n].usage*1.65+38)});return Object.entries(s).filter(([n])=>!chosen.includes(n)).sort((a,b)=>b[1]-a[1]).slice(0,8);}
function renderSynergy(){if(!S.team.length){synergies.innerHTML='<div class="card"><b>Empezá por cualquier Pokémon.</b><p class="muted">Cuando elijas uno, VGC Coach va a priorizar compañeros compatibles y explicar qué aporta cada uno.</p></div>';return}synergies.innerHTML=candidates().map(([n,v])=>{const p=findName(n);if(!p)return"";return `<div class="card" onclick="add(${p.id})"><div class="card-head">${spriteTag(p)}<h3>${cap(n)}</h3><span class="score">${v}</span></div><div class="bar"><span style="width:${Math.min(100,v)}%"></span></div><p class="muted">${META[n].roles.join(" · ")}</p></div>`}).join("");}
function renderDiagnosis(){const n=S.team.map(x=>x.name),size=n.length,speed=n.some(x=>["sneasler","salamence","farigiraf"].includes(x)),fake=n.some(x=>["rillaboom","incineroar","sneasler"].includes(x)),special=n.some(x=>["gholdengo","farigiraf"].includes(x));const a=Math.min(98,28+size*8+(special?12:0)),c=Math.min(95,20+size*7+(fake?18:0)),f=Math.min(95,22+size*8+(speed?10:0));diagnosis.innerHTML=`<div class="metric ${a>70?'good':'warn'}">Presión<b>${a}%</b></div><div class="metric ${c>65?'good':'warn'}">Control<b>${c}%</b></div><div class="metric ${f>70?'good':'warn'}">Flexibilidad<b>${f}%</b></div><div class="metric ${size==6?'good':'warn'}">Equipo<b>${size}/6</b></div>`;}
function renderGameplan(){const n=S.team.map(x=>cap(x.name)),r=n.includes("Rillaboom"),i=n.includes("Incineroar"),s=n.includes("Sneasler");gameplan.innerHTML=`<b>Plan explicado fácil</b><ul><li>Antes de atacar, pensá qué querés conseguir durante los próximos dos turnos.</li><li>${r?"Rillaboom puede generar espacio con Fake Out y Grassy Terrain.":"Identificá qué Pokémon puede comprar un turno favorable."}</li><li>${i?"Incineroar aporta Intimidate, Fake Out y reposicionamiento.":"Si te falta control, pensá en speed control, Protect o cambios."}</li><li>${s?"Sneasler aporta presión rápida: no lo arriesgues sin un motivo.":"Decidí qué Pokémon necesitás conservar para el endgame."}</li><li>En dobles no gana automáticamente quien hace más daño: importa mantener una posición favorable.</li></ul>`;}

const COACH_RULES={
 speed:['sneasler','salamence','farigiraf','tailwind','icy-wind'],
 special:['gholdengo','farigiraf','indeedee-f'],
 support:['rillaboom','incineroar','farigiraf','indeedee-f'],
 terrain:['rillaboom','indeedee-f'],
 offense:['sneasler','gholdengo','kingambit','salamence'],
 bulky:['incineroar','rillaboom','farigiraf'],
 trickroom:['farigiraf','kingambit','indeedee-f']
};
function hasAny(list){return S.team.some(p=>list.includes(p.name));}
function roleCount(list){return S.team.filter(p=>list.includes(p.name)).length;}
function teamCoachData(){const names=S.team.map(p=>p.name);const size=names.length;const speed=roleCount(COACH_RULES.speed);const special=roleCount(COACH_RULES.special);const support=roleCount(COACH_RULES.support);const offense=roleCount(COACH_RULES.offense);const terrain=roleCount(COACH_RULES.terrain);const trick=roleCount(COACH_RULES.trickroom);const style=playstyle?.value||'auto';let archetype='Balance ofensivo';if(style==='offense'||(style==='auto'&&offense>=3&&support<=2))archetype='Ofensiva';if(style==='control'||(style==='auto'&&support>=3))archetype='Control / posicionamiento';if(style==='trickroom'||(style==='auto'&&trick>=2))archetype='Trick Room / lento';const issues=[];const changes=[];
 if(size<6)issues.push({level:'info',title:'Equipo incompleto',text:`Tenés ${size}/6 Pokémon. El Coach puede orientar la estructura, pero algunas debilidades no se pueden medir hasta completar el equipo.`});
 if(size>=3&&special===0)issues.push({level:'danger',title:'Dependencia del daño físico',text:'No hay una fuente especial reconocible en el conjunto de datos del Coach. Considerá incorporar presión especial para evitar que el plan dependa de un único tipo de daño.'});
 if(size>=3&&speed===0)issues.push({level:'warn',title:'Speed control poco clara',text:'No detecto una herramienta principal de control de velocidad. Podés jugar sin ella, pero deberías tener una razón y un plan para equipos que cambien el orden de velocidad.'});
 if(size>=4&&support===0)issues.push({level:'warn',title:'Poco espacio para posicionarte',text:'No aparece una pieza clara de soporte/pivot en los roles conocidos. Revisá si tus leads pueden crear turnos seguros para tu win condition.'});
 if(size>=4&&offense>=4&&support<=1)issues.push({level:'warn',title:'Equipo muy orientado al daño',text:'Tenés mucha presión ofensiva y pocas piezas de reposicionamiento. Si no conseguís una ventaja temprana, puede costarte recuperar posición.'});
 if(size>=4&&trick===0)issues.push({level:'info',title:'Respuesta a Trick Room no identificada',text:'El Coach no detecta una herramienta dedicada en la composición actual. Eso no significa que pierdas automáticamente contra Trick Room; definí si querés impedirlo o jugar alrededor.'});
 if(terrain>=2)issues.push({level:'good',title:'Plan de terreno reconocible',text:'Hay varias piezas que interactúan con el terreno. Definí cuál se beneficia realmente y evitá gastar el recurso sin un propósito.'});
 if(hasAny(['rillaboom'])&&!hasAny(['gholdengo','kingambit','sneasler','salamence']))changes.push({from:null,to:'gholdengo',why:'Rillaboom aporta Fake Out y Grassy Terrain; una fuente de presión especial o una condición de victoria que aproveche los turnos ganados puede completar el núcleo.'});
 if(hasAny(['sneasler'])&&!hasAny(['rillaboom','incineroar','indeedee-f']))changes.push({from:null,to:'rillaboom',why:'Sneasler aprecia compañeros que le ayuden a comprar turnos o crear presión de posición. Rillaboom es una opción reconocible del núcleo cargado por el Coach.'});
 if(hasAny(['gholdengo'])&&special===1&&size>=4)changes.push({from:null,to:'farigiraf',why:'Además de aportar daño/soporte especial, Farigiraf puede ofrecer anti-prioridad y una estructura distinta para proteger la condición de victoria.'});
 if(size>=6&&speed===0)changes.push({from:null,to:'salamence',why:'Candidato para añadir presión de velocidad y una herramienta de posicionamiento; no es un reemplazo obligatorio, comparalo con alternativas antes de aceptarlo.'});
 if(size>=6&&offense>=4&&support<=1)changes.push({from: S.team.find(p=>['kingambit','sneasler'].includes(p.name))?.name||S.team[5]?.name,to:'incineroar',why:'Puede convertir parte de la presión directa en reposicionamiento mediante Intimidate, Fake Out y pivot. El cambio sacrifica daño inmediato.'});
 return {size,archetype,speed,special,support,offense,issues,changes};}
function renderTeamCoach(){if(!teamCoachSummary)return;const d=teamCoachData();const pct=x=>Math.min(100,Math.max(0,20+x*22));teamCoachSummary.innerHTML=`<div class="coach-kpi"><span>Arquetipo detectado</span><b>${d.archetype}</b></div><div class="coach-kpi"><span>Speed control</span><b>${d.speed? 'Detectada':'No clara'}</b></div><div class="coach-kpi"><span>Daño especial</span><b>${d.special? 'Detectado':'Bajo'}</b></div><div class="coach-kpi"><span>Soporte / pivot</span><b>${d.support? 'Detectado':'No claro'}</b></div>`;
 teamCoachIssues.innerHTML=d.issues.length?d.issues.map(i=>`<article class="card insight"><h3>${i.level==='danger'?'🔴':i.level==='warn'?'🟡':i.level==='good'?'🟢':'🔵'} ${i.title}</h3><p>${i.text}</p></article>`).join(''):'<article class="card insight"><h3>🟢 No apareció una alerta estructural fuerte</h3><p>Completá el equipo y después revisá matchups concretos. El Coach no trata una composición como perfecta solo porque no encuentre una alerta.</p></article>';
 teamCoachChanges.innerHTML=d.changes.length?`<h3>🔧 Cambios que vale la pena probar</h3>`+d.changes.slice(0,4).map(c=>`<article class="change"><div><h3>${c.from?cap(c.from):'Añadir candidato'}</h3><p>${c.from?'Función actual a reconsiderar':'Candidato sugerido'}</p></div><div class="arrow">→</div><div><h3>${cap(c.to)}</h3><p>${c.why}</p><button class="ghost mini" onclick="coachAdd('${c.to}')">Probar en el equipo</button></div></article>`).join(''):'<div class="card static"><b>No hay cambios automáticos sugeridos todavía.</b><p class="muted">Completá más piezas para que el Coach tenga contexto suficiente.</p></div>';
 const names=S.team.map(p=>cap(p.name));teamCoachPlan.innerHTML=`<b>🎯 Plan sugerido para ${d.archetype}</b><ul><li>Antes de cada lead, elegí una condición de victoria y una pieza que puedas sacrificar sin destruir el plan.</li><li>Con ${d.speed?`herramientas de velocidad detectadas`:'speed control no claramente detectada'}, prepará una línea específica para cuando el rival cambie el orden de velocidad.</li><li>${d.special?'Conservá al menos una fuente de daño especial cuando el rival pueda castigar equipos demasiado físicos.':'Si tu plan depende del daño físico, identificá qué Pokémon defensivos pueden frenarlo y prepará una respuesta.'}</li><li>Tu composición actual: ${names.length?names.join(', '):'todavía vacía'}.</li></ul><small class="muted">Estas recomendaciones son un motor de análisis local. No sustituyen una evaluación de un combate concreto; se recalculan cada vez que cambia el equipo.</small>`;}
function coachAdd(name){const p=findName(name);if(p&&!S.team.some(x=>x.name===name)&&S.team.length<6){S.team.push(p);S.selected=p;renderAll();}}
analyzeTeam.onclick=renderTeamCoach;playstyle.onchange=renderTeamCoach;

function renderDex(){const a=(S.selected?[S.selected]:S.all.filter(p=>META[p.name])).slice(0,20);dexGrid.innerHTML=a.map(p=>{const d=S.details.get(p.id);return `<div class="dex-card">${spriteTag(p)}<div><h3>${cap(p.name)}</h3><div class="types">${(d?.types||[]).map(t=>`<span>${t}</span>`).join("")}</div><p class="muted">${META[p.name]?`Meta cargado localmente: ${META[p.name].usage}% · ${META[p.name].roles.join(", ")}`:"Sin datos competitivos locales cargados."}</p></div></div>`}).join("");a.forEach(p=>detail(p.id));}
function makeBackground(){const m=["pikachu","eevee","cyndaquil","mudkip","sprigatito","fuecoco","quaxly","riolu","gible","shinx","lucario","sneasler","rillaboom"];runnerLayer.innerHTML=m.map((n,i)=>`<img class="runner ${i%5===0?'big':i%3===0?'small':''}" style="animation-duration:${18+i*2}s;animation-delay:-${i*3}s" src="${SHOWDOWN}${n}.gif" alt="">`).join("");}
backgroundBtn.onclick=()=>backgroundPanel.classList.toggle("hidden");document.querySelectorAll("[data-theme]").forEach(b=>b.onclick=()=>document.body.className="theme-"+b.dataset.theme);speed.oninput=()=>document.querySelectorAll(".runner").forEach((x,i)=>x.style.animationDuration=(18+i*2)/+speed.value+"s");opacity.oninput=()=>document.querySelectorAll(".runner").forEach(x=>x.style.opacity=opacity.value);let moving=true;motionBtn.onclick=()=>{moving=!moving;document.querySelectorAll(".runner").forEach(x=>x.style.animationPlayState=moving?"running":"paused");motionBtn.textContent="Animación: "+(moving?"ON":"OFF")};
const scenarios=[{q:"Tu Rillaboom está junto a Sneasler y el rival tiene una amenaza que puede dejar fuera a Sneasler. ¿Qué principio importa más?",a:["Proteger a Sneasler mientras Rillaboom compra un turno.","Atacar siempre con ambos.","Cambiar los dos sin analizar la posición."],ok:0,w:"Conservar una pieza importante mientras el compañero controla el turno puede crear una posición favorable."},{q:"El rival parece preparado para Trick Room. ¿Qué deberías pensar primero?",a:["Si conviene impedirlo o jugar alrededor de él.","Ignorarlo siempre.","Usar todos los ataques inmediatamente."],ok:0,w:"Trick Room cambia el orden de velocidad, así que primero hay que decidir si tu equipo quiere impedirlo o jugar alrededor del efecto."},{q:"Tenés ventaja de posición pero el rival puede hacer mucho daño a uno de tus Pokémon. ¿Qué idea es útil?",a:["No arriesgar una pieza importante sin necesidad.","Atacar automáticamente con los dos.","Usar el movimiento más fuerte aunque pierdas un Pokémon."],ok:0,w:"VGC premia la posición y la conservación de recursos, no solamente el daño inmediato."}];let sc;function newScenario(){sc=scenarios[Math.floor(Math.random()*scenarios.length)];scenario.innerHTML=`<h3>${sc.q}</h3>`;feedback.textContent="Elegí una línea para recibir explicación.";choices.innerHTML=sc.a.map((x,i)=>`<button class="choice" onclick="answer(${i})">${x}</button>`).join("");}function answer(i){feedback.innerHTML=i===sc.ok?`<b class="result-win">Bien.</b> ${sc.w}`:`<b class="result-loss">No es la línea que priorizaría el Coach.</b> ${sc.w}`;}
async function psFetch(url){const r=await fetch(url,{headers:{Accept:"application/json"}});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json();}
function normalizeUser(data){const u=data?.user||data;return {name:u?.userid||u?.name||username.value.trim(),avatar:u?.avatar,registertime:u?.registertime,ratings:u?.ratings||{},rooms:u?.rooms||{}};}
function chooseRating(ratings,format){if(!ratings)return null;const keys=Object.keys(ratings);const exact=ratings[format];if(exact)return exact;const vgc=keys.find(k=>/vgc|doubles/i.test(k));return vgc?ratings[vgc]:null;}
async function loadProfileData(){const user=username.value.trim();const format=(formatId.value.trim()||"gen9vgc2026regmc").replace(/[^a-zA-Z0-9_-]/g,"");if(!user){profileStatus.innerHTML='<span class="error">Escribí un nombre de Showdown.</span>';return}profileStatus.textContent="Consultando perfil y replays públicas…";try{const u=normalizeUser(await psFetch(`${PS}/users/${encodeURIComponent(user)}.json`));const reps=await psFetch(`${REPLAYS}/search.json?user=${encodeURIComponent(u.name)}&format=${encodeURIComponent(format)}`);S.profile={...u,format};saveProfileLocal();S.replays=Array.isArray(reps)?reps.filter(x=>x?.id):[];renderProfile();renderReplayList();profileStatus.textContent=`Listo: ${S.replays.length} replays encontradas para ${u.name} en ${format}.`;await analyzeReplays();}catch(e){profileStatus.innerHTML=`<span class="error">No se pudo consultar Showdown desde este navegador. ${esc(e.message)}. Probá abrir VGC Coach con el servidor local de Python y verificá el ID del formato.</span>`;}}
function replayId(r){return r.id||`${r.formatid||r.format}-${r.id}`;}
function replayUrl(r){return `${REPLAYS}/${encodeURIComponent(r.id)}.json`;}
function resultFor(r,user){const p1=(r.p1||r.player1||"").toLowerCase(),p2=(r.p2||r.player2||"").toLowerCase(),w=(r.winner||"").toLowerCase();if(!w)return"unknown";return w===user.toLowerCase()?"win":(w===p1||w===p2?"loss":"unknown");}
function renderProfile(){const user=S.profile?.name||username.value.trim();const fmt=S.profile?.format||formatId.value;const rated=chooseRating(S.profile?.ratings,fmt);const wins=S.replays.filter(r=>resultFor(r,user)==="win").length,losses=S.replays.filter(r=>resultFor(r,user)==="loss").length,total=wins+losses,wr=total?((wins/total)*100).toFixed(1):"—";profileSummary.innerHTML=`<div class="stat-card"><span>Jugador</span><b>${esc(user)}</b></div><div class="stat-card"><span>Victorias cargadas</span><b class="result-win">${wins}</b></div><div class="stat-card"><span>Derrotas cargadas</span><b class="result-loss">${losses}</b></div><div class="stat-card"><span>Winrate de replays</span><b>${wr}${total?"%":""}</b><span>${rated?`Rating: ${rated.rating??rated.elo??"—"}`:"Rating no encontrado para este ID"}</span></div>`;}
function renderReplayList(){const user=S.profile?.name||username.value.trim();if(!S.replays.length){replayList.innerHTML='<div class="replay-item"><span>No hay replays para esta búsqueda. Revisá el nombre o el formato.</span></div>';return}replayList.innerHTML=S.replays.slice(0,50).map((r,i)=>{const res=resultFor(r,user);const label=res==="win"?"VICTORIA":res==="loss"?"DERROTA":"RESULTADO";const cls=res==="win"?"result-win":res==="loss"?"result-loss":"";return `<div class="replay-item"><div><b class="${cls}">${label}</b> · <b>${esc(r.p1||"?")}</b> vs <b>${esc(r.p2||"?")}</b><div class="replay-meta">${esc(r.format||r.formatid||S.profile?.format||"")} · ${r.uploadtime?new Date(r.uploadtime*1000).toLocaleString():"fecha no disponible"}</div></div><div class="replay-actions"><button class="ghost mini" onclick="inspectReplay('${esc(r.id)}')">Analizar</button><a class="ghost mini" href="${replayUrl(r)}" target="_blank" rel="noopener">JSON</a></div></div>`}).join("");}
function getReplayById(id){return S.replays.find(r=>r.id===id);}
function summarizeLog(log,user){const lines=String(log||"").split("\n");let turns=0,ko=0,protect=0,tera=0,switches=0,moves=0;const revealed=new Set();for(const line of lines){if(line.startsWith("|turn|"))turns++;if(line.includes("|faint|"))ko++;if(/\|move\|.*\|Protect\b/i.test(line))protect++;if(/-terastallize\|/i.test(line)||/\|terastallize\|/i.test(line))tera++;if(line.includes("|switch|"))switches++;if(line.startsWith("|move|"))moves++;const sw=line.match(/\|switch\|([^|]+)/);if(sw)revealed.add(sw[1]);}return{turns,ko,protect,tera,switches,moves,revealed:[...revealed].slice(0,12)};}
async function inspectReplay(id){const r=getReplayById(id);if(!r)return;replayDetail.classList.remove("hidden");replayDetail.innerHTML='<h2>Analizando replay…</h2><p class="muted">Leyendo el log público de Showdown.</p>';try{const d=await psFetch(replayUrl(r));const s=summarizeLog(d.log||d.inputlog||d,username.value.trim());const result=resultFor(r,username.value.trim());const insights=buildReplayInsights(s,result);replayDetail.innerHTML=`<div class="section-title"><div><span class="eyebrow">REPLAY ANALYZER</span><h2>${esc(r.p1||"?")} vs ${esc(r.p2||"?")}</h2></div><a class="ghost mini" href="${REPLAYS}/${encodeURIComponent(id)}" target="_blank" rel="noopener">Abrir replay</a></div><div class="detail-grid"><div class="stat-card"><span>Resultado</span><b class="${result==='win'?'result-win':'result-loss'}">${result==='win'?'VICTORIA':result==='loss'?'DERROTA':'NO DETERMINADO'}</b></div><div class="stat-card"><span>Turnos</span><b>${s.turns}</b></div><div class="stat-card"><span>Movimientos</span><b>${s.moves}</b></div><div class="stat-card"><span>Protect usados</span><b>${s.protect}</b></div><div class="stat-card"><span>Tera detectado</span><b>${s.tera}</b></div><div class="stat-card"><span>Faints</span><b>${s.ko}</b></div></div><div class="section"><h2>Coach de esta partida</h2><div class="cards">${insights.map(x=>`<article class="lesson insight"><h3>${x.title}</h3><p>${x.text}</p></article>`).join("")}</div></div><div class="section"><h2>Datos observados</h2><p class="muted">Pokémon vistos en cambios: ${s.revealed.length?s.revealed.map(esc).join(", "):"no detectados"}. Estos datos describen el log; no son una reconstrucción perfecta del estado oculto.</p></div>`;}catch(e){replayDetail.innerHTML=`<p class="error">No se pudo leer esta replay: ${esc(e.message)}</p>`;}}
function buildReplayInsights(s,result){const a=[];if(s.turns<=3)a.push({title:"Partida muy corta",text:"La partida terminó en pocos turnos. En una muestra así, no conviene sacar conclusiones fuertes sobre tu estilo: el resultado puede depender de un intercambio temprano."});if(s.protect===0)a.push({title:"Revisá tus Protect",text:"No se detectó Protect en el log. Eso no significa automáticamente que haya sido un error, pero vale la pena revisar si hubo turnos donde proteger una pieza, explorar una decisión o esperar un efecto habría cambiado la posición."});else a.push({title:"Protect presente",text:`Se detectaron ${s.protect} usos de Protect. En la revisión manual, mirá si esos Protect consiguieron algo concreto: negar daño, gastar turnos de speed control, explorar una decisión o permitir que el compañero avance.`});if(s.switches<2)a.push({title:"Pocas rotaciones",text:"Hubo pocas acciones de cambio detectadas. Revisá si mantuviste la pareja correcta en campo o si hubo turnos donde un cambio habría conservado tu win condition."});else a.push({title:"Hubo reposicionamiento",text:`Se detectaron ${s.switches} cambios. Revisá especialmente los cambios que dejaron al compañero solo o que entregaron una posición mejor al rival.`});if(s.tera===0)a.push({title:"Tera no detectado",text:"El log no mostró una Teracristalización. Si el formato/replay usa otra mecánica o el log no la registra de esta forma, este indicador puede ser incompleto."});else a.push({title:"Recurso de Tera",text:"La partida registra una Teracristalización. Al revisar el turno, preguntate qué amenaza evitó o qué condición de victoria habilitó."});a.push({title:result==='win'?"No te quedes solo con la victoria":"No te quedes solo con la derrota",text:result==='win'?"Una victoria puede contener líneas mejorables. Buscá el primer turno donde tu posición dejó de ser claramente favorable.":"Una derrota no significa que todo haya estado mal. Buscá el primer cambio de posición y separá ese momento de los errores posteriores."});return a;}
async function analyzeReplays(){
 if(!S.replays.length){renderPlayerAnalytics([]);return}
 const user=S.profile.name; const rows=[]; let fetched=0;
 for(const r of S.replays.slice(0,50)){
   const result=resultFor(r,user);
   try{const d=await psFetch(replayUrl(r));const log=d.log||d.inputlog||d;const s=summarizeLog(log,user);rows.push({...s,result,id:r.id,date:r.uploadtime||0,p1:r.p1||"?",p2:r.p2||"?"});fetched++;}catch{}
 }
 S.replayStats=rows; renderPlayerAnalytics(rows);
 const wins=rows.filter(x=>x.result==='win'),losses=rows.filter(x=>x.result==='loss');
 const insights=[];
 if(rows.length<5) insights.push({title:"Muestra pequeña",text:`El Coach pudo leer ${rows.length} replays. Tomá estos patrones como señales, no como conclusiones definitivas.`});
 if(losses.length>wins.length && rows.length>=5) insights.push({title:"Las derrotas dominan esta muestra",text:`En las replays analizadas hay ${wins.length} victorias y ${losses.length} derrotas. El siguiente paso es revisar qué patrones se repiten dentro de las derrotas, no asumir que existe una única causa.`});
 const noProtect=rows.filter(x=>x.protect===0).length;
 if(rows.length>=5 && noProtect/rows.length>=.45) insights.push({title:"Protect aparece poco",text:`${Math.round(noProtect/rows.length*100)}% de las replays analizadas no contienen un Protect de tu lado detectado por el parser. Revisá si tus equipos y situaciones realmente pedían más conservación o exploración.`});
 const avgT=rows.reduce((a,x)=>a+x.turns,0)/rows.length;
 if(rows.length>=5 && avgT<6) insights.push({title:"Tus partidas tienden a decidirse temprano",text:`Promedio aproximado: ${avgT.toFixed(1)} turnos. Eso puede venir de leads explosivos, matchups muy polarizados o errores tempranos; hace falta mirar los turnos críticos para distinguirlos.`});
 const avgS=rows.reduce((a,x)=>a+x.switches,0)/rows.length;
 if(rows.length>=5) insights.push({title:"Reposicionamiento",text:`Promedio aproximado: ${avgS.toFixed(1)} cambios detectados por partida. Compará este dato con tus victorias y derrotas para estudiar cuándo los cambios te compran posición y cuándo entregan tempo.`});
 if(!insights.length) insights.push({title:"Todavía no hay un patrón fuerte",text:"Cargá más partidas y mantené el mismo formato para que las comparaciones sean más útiles."});
 playerInsights.innerHTML=insights.map(x=>`<article class="card insight"><h3>${x.title}</h3><p>${x.text}</p></article>`).join("");
}
function renderPlayerAnalytics(rows){
 if(!rows.length){playerMetrics.innerHTML='<div class="stat-card"><span>Replays leídas</span><b>0</b></div>';progressBars.innerHTML='';patternGrid.innerHTML='<article class="pattern"><h3>Sin datos todavía</h3><p>Cargá un perfil y sus replays públicas para empezar a construir tu historial.</p></article>';return;}
 const wins=rows.filter(x=>x.result==='win').length, losses=rows.filter(x=>x.result==='loss').length, total=wins+losses;
 const avg=(key)=>rows.reduce((a,x)=>a+(Number(x[key])||0),0)/rows.length;
 const wr=total?wins/total*100:0, ppg=avg('protect'), spg=avg('switches'), tpg=avg('tera'), turns=avg('turns');
 playerMetrics.innerHTML=[['Replays leídas',rows.length],['Victorias',wins],['Derrotas',losses],['Winrate',total?wr.toFixed(1)+'%':'—'],['Turnos / partida',turns.toFixed(1)],['Protect / partida',ppg.toFixed(1)]].map(x=>`<div class="stat-card"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('');
 const bars=[['Winrate de la muestra',wr],['Partidas con Protect',rows.filter(x=>x.protect>0).length/rows.length*100],['Partidas con Tera detectado',rows.filter(x=>x.tera>0).length/rows.length*100],['Partidas con 2+ cambios',rows.filter(x=>x.switches>=2).length/rows.length*100],['Partidas de 6+ turnos',rows.filter(x=>x.turns>=6).length/rows.length*100]];
 progressBars.innerHTML=bars.map(([n,v])=>`<div class="progress-row"><span>${n}</span><div class="progress-track"><span style="width:${Math.max(0,Math.min(100,v))}%"></span></div><b>${v.toFixed(0)}%</b></div>`).join('');
 const winAvg=k=>{const a=rows.filter(x=>x.result==='win');return a.length?a.reduce((s,x)=>s+x[k],0)/a.length:0}; const lossAvg=k=>{const a=rows.filter(x=>x.result==='loss');return a.length?a.reduce((s,x)=>s+x[k],0)/a.length:0};
 const patterns=[
  ['Turnos en victorias',winAvg('turns').toFixed(1),`Promedio de turnos en las ${wins} victorias analizadas.`],
  ['Turnos en derrotas',lossAvg('turns').toFixed(1),`Promedio de turnos en las ${losses} derrotas analizadas.`],
  ['Protect en victorias',winAvg('protect').toFixed(1),`Usos detectados por victoria, no una recomendación automática.`],
  ['Protect en derrotas',lossAvg('protect').toFixed(1),`Usos detectados por derrota.`],
  ['Cambios por partida',spg.toFixed(1),`Promedio de cambios detectados.`],
  ['Tera por partida',tpg.toFixed(1),`Eventos de Teracristalización detectados.`]
 ];
 patternGrid.innerHTML=patterns.map(x=>`<article class="pattern"><h3>${x[0]}</h3><div class="big">${x[1]}</div><p>${x[2]}</p></article>`).join('');
}
function saveProfileLocal(){if(!S.profile)return;localStorage.setItem('vgcCoachProfile',JSON.stringify({name:S.profile.name,format:S.profile.format,savedAt:Date.now()}));}
function restoreProfileLocal(){try{const x=JSON.parse(localStorage.getItem('vgcCoachProfile')||'null');if(x?.name){username.value=x.name;formatId.value=x.format||formatId.value;profileStatus.textContent='Perfil recordado localmente. Cargalo para actualizar los datos públicos.';}}catch{}}
function exportReport(){if(!S.profile)return;const report={generatedAt:new Date().toISOString(),player:S.profile.name,format:S.profile.format,replaysRead:S.replayStats.length,stats:S.replayStats,notes:'Estadísticas calculadas a partir de replays públicas detectadas por VGC Coach. No representan necesariamente todo el historial del jugador.'};const blob=new Blob([JSON.stringify(report,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`vgc-coach-${S.profile.name.replace(/[^a-z0-9_-]/gi,'_')}-report.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
loadProfile.onclick=loadProfileData;refreshReplays.onclick=()=>{if(S.profile)loadProfileData();};document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.getElementById(b.dataset.tab).classList.add("active")});search.oninput=renderList;typeFilter.onchange=renderList;genFilter.onchange=renderList;metaOnly.onchange=renderList;clear.onclick=()=>{S.team=[];S.selected=null;renderAll()};
newScenario.onclick=newScenario;
exportReport.onclick=exportReport;
forgetProfile.onclick=()=>{localStorage.removeItem('vgcCoachProfile');username.value='';profileStatus.textContent='Datos locales borrados. Las replays públicas de Showdown no se modifican.';};
restoreProfileLocal();

// Competitive prototype: persistent local rating and simulated queue.
const RANKS=[{name:'Novato I',min:0,icon:'N'},{name:'Novato II',min:900,icon:'N'},{name:'Entrenador I',min:1000,icon:'E'},{name:'Entrenador II',min:1100,icon:'E'},{name:'Competidor I',min:1200,icon:'C'},{name:'Competidor II',min:1300,icon:'C'},{name:'Élite I',min:1400,icon:'E'},{name:'Élite II',min:1500,icon:'E'},{name:'Maestro I',min:1600,icon:'M'},{name:'Maestro II',min:1750,icon:'M'},{name:'Campeón',min:1900,icon:'C'}];
const RANK_KEY='vgcCoachRankedV1'; const rankedDefault={rating:1000,wins:0,losses:0,season:1,history:[]};
function loadRank(){try{return {...rankedDefault,...JSON.parse(localStorage.getItem(RANK_KEY)||'{}')}}catch{return {...rankedDefault}}} let ranked=loadRank();
function currentRank(){let r=RANKS[0];for(const x of RANKS)if(ranked.rating>=x.min)r=x;return r} function nextRank(){return RANKS.find(x=>x.min>ranked.rating)||null}
function renderRank(){const r=currentRank(),n=nextRank(),base=r.min,next=n?.min||base+100,pct=n?Math.max(0,Math.min(100,(ranked.rating-base)/(next-base)*100)):100;rankBadge.textContent=r.icon;rankName.textContent=r.name;rankRating.textContent=`${ranked.rating} Rating · ${ranked.wins}–${ranked.losses}`;rankProgressText.textContent=n?`${Math.max(0,ranked.rating-base)} / ${next-base}`:'Rango máximo';rankProgressBar.style.width=pct+'%';seasonLabel.textContent=`Temporada local ${ranked.season}`;rankHistory.innerHTML=ranked.history.length?ranked.history.slice().reverse().map(h=>`<div class="replay-item"><div><b class="${h.result==='win'?'result-win':'result-loss'}">${h.result==='win'?'VICTORIA':'DERROTA'}</b><div class="replay-meta">${esc(h.opponent)} · ${h.mode} · ${h.delta>=0?'+':''}${h.delta} rating</div></div><b>${h.rating}</b></div>`).join(''):'<div class="replay-item"><span class="muted">Todavía no hay partidas Ranked en este dispositivo.</span></div>'}
function saveRank(){localStorage.setItem(RANK_KEY,JSON.stringify(ranked));renderRank()}
function renderBattleRoom(mode,win,opp){battleRoom.innerHTML=`<div class="battle-top"><div><span class="muted">VGC Coach ${mode==='ranked'?'Ranked':'Casual'}</span><h3>Tu equipo <span class="versus">VS</span> CoachBot</h3></div><div class="battle-result ${win?'win':'loss'}">${win?'VICTORIA':'DERROTA'}</div></div><div class="battle-board"><div class="side"><b>Vos</b><div class="mini-team">${S.team.length?S.team.slice(0,6).map(spriteTag).join(''):'Elegí un equipo en Constructor'}</div></div><div class="versus-mark">VS</div><div class="side"><b>CoachBot · ${opp} rating</b><div class="mini-team">${['rillaboom','incineroar','gholdengo','salamence'].map(n=>{const p=findName(n);return p?spriteTag(p):''}).join('')}</div></div></div><div class="coach"><b>Coach post-partida</b><ul><li>Resultado registrado en el historial local.</li><li>En la versión online, una Ranked generará una replay real.</li><li>El análisis avanzado por turno llegará con el Coach Engine.</li></ul></div>`}
function simulateQueue(mode){queueRanked.disabled=true;queueCasual.disabled=true;queueStatus.textContent='Buscando rival…';setTimeout(()=>{const gap=Math.floor(Math.random()*81)-40,opp=Math.max(800,ranked.rating+gap),win=Math.random()>=.45,delta=mode==='ranked'?(win?Math.max(12,Math.round(25-Math.abs(gap)/8)):-Math.max(10,Math.round(21-Math.abs(gap)/10))):0;if(mode==='ranked'){ranked.rating=Math.max(0,ranked.rating+delta);win?ranked.wins++:ranked.losses++;ranked.history.push({result:win?'win':'loss',opponent:`CoachBot-${Math.floor(100+Math.random()*900)}`,mode:'Ranked',delta,rating:ranked.rating});ranked.history=ranked.history.slice(-30);saveRank()}queueStatus.innerHTML=`<b>${mode==='ranked'?'Partida simulada completada':'Partida casual simulada'}</b> · ${win?'Victoria':'Derrota'}${mode==='ranked'?` · ${delta>=0?'+':''}${delta} rating`:''}`;renderBattleRoom(mode,win,opp);queueRanked.disabled=false;queueCasual.disabled=false},850)}
queueRanked.onclick=()=>{ if(location.protocol!=='file:') queueOnline(); else simulateQueue('ranked'); };queueCasual.onclick=()=>simulateQueue('casual');
function packTeam(){return S.team.map((p,i)=>`${cap(p.name)}|${p.name}||||Jolly|4,252,0,0,0,252|||||||||`).join(']');}
let battleSocket=null;function connectBattle(){if(battleSocket&&battleSocket.readyState===1)return battleSocket;battleSocket=new WebSocket(`ws://${location.host}`);battleSocket.onmessage=e=>{const m=JSON.parse(e.data);if(m.type==='queued')queueStatus.textContent=`En cola… posición ${m.position}`;if(m.type==='matched'){queueStatus.textContent=`Rival encontrado: ${m.opponent}`;battleRoom.innerHTML=`<div class="coach"><b>Batalla online conectada</b><p class="muted">Sala ${m.room} · ${m.side}. Los mensajes del simulador aparecerán abajo.</p><div id="battleProtocol" class="protocol"></div><div id="battleChoices" class="choices"></div></div>`}if(m.type==='protocol'){const el=document.getElementById('battleProtocol');if(el){el.textContent+=(el.textContent?'\n':'')+m.data;el.scrollTop=el.scrollHeight;parseBattleRequest(m.data)}}if(m.type==='ended')queueStatus.textContent='Batalla finalizada.';if(m.type==='error')queueStatus.textContent='Error: '+m.message};return battleSocket;}
function parseBattleRequest(data){const match=String(data).match(/\|request\|(.+)/s);if(!match)return;let req;try{req=JSON.parse(match[1])}catch{return}const box=document.getElementById('battleChoices');if(!box)return;box.innerHTML='';(req.active||[]).forEach((a,i)=>{(a?.moves||[]).forEach((mv,j)=>{const b=document.createElement('button');b.className='choice';b.textContent=`P${i+1}: ${mv.name||mv.move}`;b.onclick=()=>battleSocket?.send(JSON.stringify({type:'choice',choice:`move ${j+1}`}));box.appendChild(b)})});(req.side?.pokemon||[]).forEach((p,i)=>{if(p.condition&& !/^0 fnt/i.test(p.condition)){const b=document.createElement('button');b.className='choice';b.textContent=`Cambiar → ${p.ident||p.details||i+1}`;b.onclick=()=>battleSocket?.send(JSON.stringify({type:'choice',choice:`switch ${i+1}`}));box.appendChild(b)}})}
function queueOnline(){if(S.team.length<4){queueStatus.textContent='Elegí al menos 4 Pokémon antes de buscar una batalla online.';return}const ws=connectBattle();const send=()=>ws.send(JSON.stringify({type:'queue',name:username.value.trim()||'CoachPlayer',team:packTeam()}));if(ws.readyState===1)send();else ws.addEventListener('open',send,{once:true});queueStatus.textContent='Conectando con el servidor de batalla…'}
resetRank.onclick=()=>{ranked={...rankedDefault,history:[]};saveRank();queueStatus.textContent='Perfil competitivo local reiniciado.';battleRoom.innerHTML='<div class="battle-empty"><b>No hay una batalla activa.</b><p class="muted">Perfil reiniciado.</p></div>'};renderRank();

boot();
